-- Create drivers table
CREATE TABLE IF NOT EXISTS public.drivers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    phone TEXT NOT NULL UNIQUE,
    vehicle_info TEXT,
    status TEXT DEFAULT 'pending', -- pending, approved, rejected
    is_online BOOLEAN DEFAULT false,
    current_location JSONB, -- { lat, lng }
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create customers table if not exists
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT
);

-- Update customers table
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS address JSONB;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS total_orders INTEGER DEFAULT 0;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS last_order_date TIMESTAMP WITH TIME ZONE;

-- Update orders table
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'table'; -- table, delivery, takeout
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_id BIGINT REFERENCES public.customers(id);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS delivery_address JSONB;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS driver_id UUID REFERENCES public.drivers(id);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_method TEXT; -- stripe, cash, pix
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending'; -- pending, paid, failed
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS stripe_session_id TEXT;

-- Enable RLS for new tables
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

-- Create policies (simplified for this example)
DROP POLICY IF EXISTS "Allow public read access on drivers" ON public.drivers;
CREATE POLICY "Allow public read access on drivers" ON public.drivers FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on drivers" ON public.drivers;
CREATE POLICY "Allow public insert on drivers" ON public.drivers FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update on drivers" ON public.drivers;
CREATE POLICY "Allow public update on drivers" ON public.drivers FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public read access on customers" ON public.customers;
CREATE POLICY "Allow public read access on customers" ON public.customers FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert on customers" ON public.customers;
CREATE POLICY "Allow public insert on customers" ON public.customers FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update on customers" ON public.customers;
CREATE POLICY "Allow public update on customers" ON public.customers FOR UPDATE USING (true);
