import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { useEffect } from 'react';
import { supabase } from './lib/supabase';

// Layouts
import AdminLayout from './layouts/AdminLayout';
import CustomerLayout from './layouts/CustomerLayout';

// Admin Pages
import Dashboard from './pages/admin/Dashboard';
import Orders from './pages/admin/Orders';
import Products from './pages/admin/Products';
import Categories from './pages/admin/Categories';
import Customers from './pages/admin/Customers';
import Inventory from './pages/admin/Inventory';
import Checkout from './pages/admin/Checkout';
import Reports from './pages/admin/Reports';
import Login from './pages/admin/Login';
import Tables from './pages/admin/Tables';
import Staff from './pages/admin/Staff';
import Kitchen from './pages/admin/Kitchen';
import Waiter from './pages/admin/Waiter';
import Drivers from './pages/admin/Drivers';

// Customer Pages
import Menu from './pages/customer/Menu';
import Cart from './pages/customer/Cart';
import OrderStatus from './pages/customer/OrderStatus';
import TableLogin from './pages/customer/TableLogin';
import OnlineLogin from './pages/customer/OnlineLogin';
import PixPayment from './pages/customer/PixPayment';

// Driver Pages
import DriverLogin from './pages/driver/DriverLogin';
import DriverDashboard from './pages/driver/DriverDashboard';

export default function App() {
  useEffect(() => {
    const setupDb = async () => {
      await supabase.rpc('exec_sql', {
        query: `
          CREATE TABLE IF NOT EXISTS staff (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name TEXT NOT NULL,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            role TEXT NOT NULL CHECK (role IN ('admin', 'cook', 'waiter')),
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
          );
          
          INSERT INTO staff (name, username, password, role)
          VALUES ('Administrador', 'admin', 'admin', 'admin')
          ON CONFLICT (username) DO NOTHING;

          ALTER TABLE tables ADD COLUMN IF NOT EXISTS needs_waiter BOOLEAN DEFAULT false;

          CREATE TABLE IF NOT EXISTS drivers (
              id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
              name TEXT NOT NULL,
              phone TEXT NOT NULL UNIQUE,
              password TEXT,
              vehicle_info TEXT,
              status TEXT DEFAULT 'pending',
              is_online BOOLEAN DEFAULT false,
              current_location JSONB,
              created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
          );
          
          ALTER TABLE drivers ALTER COLUMN password DROP NOT NULL;

          CREATE TABLE IF NOT EXISTS customers (
              id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
              name TEXT NOT NULL,
              phone TEXT,
              email TEXT
          );

          ALTER TABLE customers ADD COLUMN IF NOT EXISTS address JSONB;
          ALTER TABLE customers ADD COLUMN IF NOT EXISTS total_orders INTEGER DEFAULT 0;
          ALTER TABLE customers ADD COLUMN IF NOT EXISTS last_order_date TIMESTAMP WITH TIME ZONE;

          ALTER TABLE orders ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'table';
          ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_id BIGINT REFERENCES customers(id);
          ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_address JSONB;
          ALTER TABLE orders ADD COLUMN IF NOT EXISTS driver_id UUID REFERENCES drivers(id);
          ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method TEXT;
          ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending';
          ALTER TABLE orders ADD COLUMN IF NOT EXISTS stripe_session_id TEXT;
          
          NOTIFY pgrst, 'reload schema';
        `
      });
    };
    setupDb();
  }, []);

  return (
    <BrowserRouter>
      <Routes>
        {/* Admin Routes */}
        <Route path="/admin/login" element={<Login />} />
        <Route path="/admin/kitchen" element={<Kitchen />} />
        <Route path="/admin/waiter" element={<Waiter />} />
        <Route path="/admin" element={<AdminLayout />}>
          <Route index element={<Navigate to="/admin/dashboard" replace />} />
          <Route path="dashboard" element={<Dashboard />} />
          <Route path="orders" element={<Orders />} />
          <Route path="products" element={<Products />} />
          <Route path="categories" element={<Categories />} />
          <Route path="customers" element={<Customers />} />
          <Route path="inventory" element={<Inventory />} />
          <Route path="tables" element={<Tables />} />
          <Route path="checkout" element={<Checkout />} />
          <Route path="reports" element={<Reports />} />
          <Route path="staff" element={<Staff />} />
          <Route path="drivers" element={<Drivers />} />
        </Route>

        {/* Driver Routes */}
        <Route path="/driver/login" element={<DriverLogin />} />
        <Route path="/driver/dashboard" element={<DriverDashboard />} />

        {/* Customer Routes */}
        <Route path="/login" element={<TableLogin />} />
        <Route path="/online" element={<OnlineLogin />} />
        <Route path="/" element={<CustomerLayout />}>
          <Route index element={<Menu />} />
          <Route path="cart" element={<Cart />} />
          <Route path="status" element={<OrderStatus />} />
          <Route path="pix-payment/:orderId" element={<PixPayment />} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}
